//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleJournal.SharedResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleJournal.SharedResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENTION!.
        /// </summary>
        public static string strAttention {
            get {
                return ResourceManager.GetString("strAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chequered.
        /// </summary>
        public static string strChequered {
            get {
                return ResourceManager.GetString("strChequered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dotted.
        /// </summary>
        public static string strDottet {
            get {
                return ResourceManager.GetString("strDottet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while analysing: {0}. Make sure SimpleJournal is installed correctly!.
        /// </summary>
        public static string strErrorMessageAnalyzingStrokes {
            get {
                return ResourceManager.GetString("strErrorMessageAnalyzingStrokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading settings:.
        /// </summary>
        public static string strFailedToLoadSettings {
            get {
                return ResourceManager.GetString("strFailedToLoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when saving the settings:.
        /// </summary>
        public static string strFailedToSaveSettings {
            get {
                return ResourceManager.GetString("strFailedToSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set file association: {0}.
        /// </summary>
        public static string strFailedToSetFileAssoc_Message {
            get {
                return ResourceManager.GetString("strFailedToSetFileAssoc_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while transforming the shape:.
        /// </summary>
        public static string strFailedToTransformShape {
            get {
                return ResourceManager.GetString("strFailedToTransformShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        public static string strLandscape {
            get {
                return ResourceManager.GetString("strLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blanco.
        /// </summary>
        public static string strPlain {
            get {
                return ResourceManager.GetString("strPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        public static string strPortrait {
            get {
                return ResourceManager.GetString("strPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruled.
        /// </summary>
        public static string strRuled {
            get {
                return ResourceManager.GetString("strRuled", resourceCulture);
            }
        }
    }
}
